server {
    listen 80 default_server;
    server_name _;

    return 444;  # Закрыть соединение без ответа
}

# Блокировка по HTTPS (порт 443)
# server {
#     listen 443 ssl default_server;
#     listen [::]:443 ssl default_server;
#     server_name _;

#     # Указываем твои существующие сертификаты (взял пути из твоего конфига dev6), 
#     # чтобы Nginx не ругался при старте на отсутствие SSL-клиента
#     # ssl_certificate /etc/letsencrypt/live/dev6.savin-it.ru/fullchain.pem;
#     # ssl_certificate_key /etc/letsencrypt/live/dev6.savin-it.ru/privkey.pem;

#     return 444;  # Точно так же жестко рвем соединение
# }