server {
    listen 80;
    listen [::]:80;
    server_name dev6.savin-it.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name dev6.savin-it.ru;

    ssl_certificate /etc/nginx/ssl/selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/selfsigned.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location /react-tables/ {
        alias /var/www/react-tables/;
        index index.html;
        try_files $uri $uri/ /react-tables/index.html;
    }

    location /api/ {
        proxy_pass http://python:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /health {
        proxy_pass http://python:8000/health;
    }

    location = / {
        return 301 /react-tables/;
    }
}